import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [urlInput, setUrlInput] = useState<string>("");

  const sendRequest = (e: React.ChangeEvent<HTMLFormElement>) => {
    // Sends URL to fetch images/data
    e.preventDefault();
    console.log({ urlInput });
    fetch(`/api/webscrape/?url_input='${urlInput}'`)
      .then((res) => res.json())
      .catch((err) => console.log({ err }));
  };

  const validateForm = (e: React.ChangeEvent<HTMLInputElement>) => {
    // Sets url input/validates form, needs to disable submit if not actual url

    setUrlInput(e.target.value);
    let input = e.target.value;

    // http://www.faqs.org/rfcs/rfc3987.html - Reference
    let expression =
      /[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)?/gi;
    let regex = new RegExp(expression);

    let test = input.match(regex);
    console.log({ test });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form onSubmit={sendRequest}>
        Home Page
        <div>
          <label htmlFor="url-input">This is the input</label>
          <input
            type="text"
            name="url-input"
            className="w-3 min-w-full border-2 border-solid"
            onChange={(e) => validateForm(e)}
          />
        </div>
        <button type="submit">Submit</button>
      </form>
    </>
  );
}
