import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useMemo, useState } from "react";
import TextCountChart from "../components/TextCountChart";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [urlInput, setUrlInput] = useState<string>("");
  const [imageResults, setImageResults] = useState([]);
  const [textResults, setTextResults] = useState([]);
  const [errorMessage, setErrorMessage] = useState();

  const sendRequest = async (e: React.ChangeEvent<HTMLFormElement>) => {
    // Sends URL to fetch images/data
    e.preventDefault();

    let results = await fetch(`/api/webscrape/?url_input='${urlInput}'`)
      .then((res) => res.json())
      .catch((err) => console.log({ err }));

    if (results?.images) {
      setImageResults(results.images);
    }

    if (results?.sortedWordMap) {
      setTextResults(results.sortedWordMap);
    }
  };

  const validateForm = (e: React.ChangeEvent<HTMLInputElement>) => {
    // Sets url input/validates form, needs to disable submit if not actual url

    setUrlInput(e.target.value);
    let input = e.target.value;

    // http://www.faqs.org/rfcs/rfc3987.html - Reference
    let expression =
      /[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)?/gi;
    let regex = new RegExp(expression);

    let test = input.match(regex);
    console.log({ test });
  };

  const PhotoGallery = useMemo(() => {
    if (!imageResults) return [];

    return imageResults.map((image, idx) => {
      return (
        <div className="min-w-full" key={image + idx.toString()}>
          <Image src={image} height={90} width={90} alt="image" />
        </div>
      );
    });
  }, [imageResults]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form onSubmit={sendRequest}>
        Home Page
        <div>
          <label htmlFor="url-input">This is the input</label>
          <input
            type="text"
            name="url-input"
            className="w-3 min-w-full border-2 border-solid"
            onChange={(e) => validateForm(e)}
          />
        </div>
        <button type="submit">Submit</button>
      </form>

      <div className="w-3 min-w-full">
        {textResults && (
          <div className="min-w-full">
            <TextCountChart data={textResults} />
          </div>
        )}
        Photos
        <div className="grid">{PhotoGallery}</div>
      </div>
    </div>
  );
}
